databases:
  - name: myrailssite
    databaseName: myrailssite
    user: myrailssite

services:
  - type: web
    name: myrailssite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrailssite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - fromGroup: sample-test-new
